// Generated by Resume Game Setup Wizard
// Edit this file or re-run setup.html to regenerate.
window.GAME_CONFIG = {
  "title": "Your Name's Resume Game",
  "description": "An interactive resume — explore the map and talk to the characters to learn more about me.",
  "npcs": [
    {
      "sprite": "villager_3",
      "tileX": 5,
      "tileY": 6,
      "patrolRange": 48,
      "speed": 24,
      "dialogues": [
        "Hi! I'm a friend of [Your Name].",
        "They're amazing at [skill].",
        "You should definitely talk to them!"
      ]
    },
    {
      "sprite": "villager_4",
      "tileX": 22,
      "tileY": 10,
      "patrolRange": 48,
      "speed": 24,
      "dialogues": [
        "I worked with [Name] on [project].",
        "They pick things up really fast.",
        "I wonder where they'll go next."
      ]
    },
    {
      "sprite": "villager_6",
      "tileX": 3,
      "tileY": 15,
      "patrolRange": 20,
      "speed": 24,
      "dialogues": [
        "Hi, I'm [name] — I met [them] through [context].",
        "One thing that stands out is [quality].",
        "You're lucky to have found them."
      ]
    },
    {
      "sprite": "villager_2",
      "tileX": 20,
      "tileY": 20,
      "patrolRange": 0,
      "speed": 0,
      "dialogues": [
        "Here's a fun fact about [Name].",
        "They once [interesting thing].",
        "Pretty impressive, right?"
      ]
    }
  ]
};
